# Generated by Django 4.1.6 on 2023-02-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=200, verbose_name='name')),
                ('web_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Not required', null=True, verbose_name='description')),
                ('unique_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='stock keeping price', max_length=20, null=True, unique=True)),
                ('upi', models.CharField(help_text='universal product id', max_length=30, null=True, unique=True)),
                ('store_price', models.IntegerField(help_text='price must not be less than 0', verbose_name='Regular store price')),
                ('sale_price', models.IntegerField(help_text='price must not be less than 0', verbose_name='sale price')),
                ('is_active', models.BooleanField(default=True, help_text='checking: True= Product visible', verbose_name='product visibility')),
                ('is_default', models.BooleanField(default=False, help_text='Format: true= sub product selected', verbose_name='default selection')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date sub-product created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date sub-product updated')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product')),
            ],
        ),
    ]
