# Generated by Django 4.1.6 on 2023-02-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='inventory last stock check date')),
                ('units', models.IntegerField(default=0, verbose_name='units/qty of stock')),
                ('units_sold', models.IntegerField(default=0, verbose_name='units sold to date')),
                ('product_inventory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='product_inventory', to='store.productinventory')),
            ],
        ),
    ]
