# Generated by Django 4.1.6 on 2023-03-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_image_alter_media_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_price',
            field=models.IntegerField(default=80000, help_text='price must not be less than 0', verbose_name='main price'),
            preserve_default=False,
        ),
    ]
